// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ipchhgklmkjslrzmssnp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlwY2hoZ2tsbWtqc2xyem1zc25wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNjU0MzYsImV4cCI6MjA2NDY0MTQzNn0.nC7-TkO7FfMC7-EnXM7pVyIWfRWJ0-CzLatX_15XKMU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);